= The Basic Reproduction Number

The basic reproduction number, denoted $R_0$, is the expected number of cases directly generated by one case in a population where all individuals are susceptible to infection.

== Definition

$R_0$ is not a biological constant for a pathogen as it is also affected by other factors such as environmental conditions and the behaviour of the infected population.

In the SIR model, $R_0$ is derived as:

$ R_0 = frac(beta, gamma) $

== Interpretation

- If $R_0 < 1$, the infection will die out in the long run.
- If $R_0 > 1$, the infection will be able to spread in a population.
