= The Basic Reproduction Number

The basic reproduction number, denoted $R_0$, is the expected number of cases directly generated by one case in a population where all individuals are susceptible to infection.

== Definition

$R_0$ is not a biological constant for a pathogen as it is also affected by other factors such as environmental conditions and the behaviour of the infected population.

In the SIR model, $R_0$ is derived as:

$ R_0 = frac(beta, gamma) $

== Derivation for SIR Model

For an epidemic to occur, the number of infected individuals must increase, meaning $d I / d t > 0$. From the SIR equations:

$
  frac(d I, d t) = beta S I - gamma I = (beta S - gamma) I
$

Thus, $d I / d t > 0$ if and only if $beta S - gamma > 0$, or:

$
  S > frac(gamma, beta)
$

At the start of an epidemic, almost everyone is susceptible, so $S approx N$. Therefore, the condition for spread is:

$
  N > frac(gamma, beta) arrow.double frac(beta N, gamma) > 1
$

Often, $beta$ is defined as the transmission rate per contact, so the force of infection is $beta S I / N$. In this formulation (used in our code), the condition becomes:

$
  frac(beta S I, N) - gamma I > 0 arrow.double frac(beta S, N) - gamma > 0
$

With $S approx N$, this simplifies to $beta - gamma > 0$, or $beta / gamma > 1$. So in our specific model formulation:

$
  R_0 = frac(beta, gamma)
$

== Estimation from Growth Rate

In the early phase of an epidemic, $S approx N$ (constant). The equation for $I$ becomes:

$
  frac(d I, d t) approx (beta - gamma) I = r I
$

where $r = beta - gamma$ is the exponential growth rate. The solution is $I(t) = I_0 e^(r t)$.

We can relate $R_0$ to the growth rate $r$:

$
  R_0 = frac(beta, gamma) = frac(r + gamma, gamma) = 1 + frac(r, gamma)
$

This allows us to estimate $R_0$ if we know the growth rate $r$ (from case data) and the recovery rate $gamma$ (from clinical data). The doubling time $T_d$ is related to $r$ by $T_d = ln(2) / r$.

== Computational Estimation

We can estimate the growth rate $r$ from early epidemic data and use it to calculate $R_0$.

=== Julia Example

```julia
using LsqFit

# Synthetic data (early exponential growth)
t = 0:1:10
I_data = 10 .* exp.(0.5 .* t) # r = 0.5

# Model: I(t) = I0 * exp(r * t)
@. model(t, p) = p[1] * exp(p[2] * t)
p0 = [10.0, 0.5]

fit = curve_fit(model, t, I_data, p0)
r_est = fit.param[2]
gamma = 0.1
R0_est = 1 + r_est / gamma
println("Estimated R0: ", R0_est)
```

=== Python Example

```python
import numpy as np
from scipy.optimize import curve_fit

# Synthetic data
t = np.arange(0, 11)
I_data = 10 * np.exp(0.5 * t)

# Model
def model(t, I0, r):
    return I0 * np.exp(r * t)

popt, pcov = curve_fit(model, t, I_data)
r_est = popt[1]
gamma = 0.1
R0_est = 1 + r_est / gamma
print(f"Estimated R0: {R0_est:.4f}")
```

== Interpretation

- If $R_0 < 1$, the infection will die out in the long run.
- If $R_0 > 1$, the infection will be able to spread in a population.
